# Goal
int32 graspable_body_id

Planner planner
SearchEnergy search_energy
SearchSpace search_space

int32 max_steps
---
# Result
Grasp[] grasps
float64[] energies
SearchEnergy search_energy
---
# Feedback 
Grasp[] grasps
float64[] energies
SearchEnergy search_energy